version: "3"

volumes:
  # TODO reinstate gen dir
  # gen:
  _build:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/opt/app
      # - gen:/opt/app/gen
      - _build:/opt/app/_build
    environment:
      - DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
    network_mode: host
    # command: bash -c "rebar3 release && _build/default/rel/hello_world/bin/hello_world foreground"
    command: ./watch.sh
    # TODO remove these options, a) move to docker image b) investigate rebar
    # https://gist.github.com/tsloughter/87bd86c19b3f805240b5682fbfe3501e
    # tty: true
    # stdin_open: true

  db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    network_mode: host
