version: "3"

volumes:
  # TODO reinstate gen dir
  # gen:
  _build:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app
      # - gen:/opt/app/gen
      - _build:/opt/app/_build
    network_mode: host
    command: rebar3 shell
    tty: true
    stdin_open: true
